<a href="https://colab.research.google.com/github/ViniLaraS/MetodosNumericosPGEQ/blob/main/Elimina_Gauss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import time
import matplotlib.pyplot as plt
import numpy.linalg as npla

########################################################
# Function to decompose the matrix
# in an upper triangular form
########################################################

def LU(A,f):
  # get the size of the system
  n = len(f)
  
  # check the size
  
  if (A.shape[0] != n) or (A.shape[1] != n):
    print('\t Inconsistent size in LU decomposition')
    info = 0
    return M,info

  # create the augmented matrix
  M = np.zeros((n,n+1))
  M[:,:-1] = A
  M[:,-1] = f

  # loop through all the colum
  # to get rid of the lower part
  for iC in range(n-1):
    # for each column loop over all the lines
    # that are below the diagonal
    # to set to 0 their elements
    for iL in range(iC+1,n):
      # check if the diagonal element
      # is null
      if(M[iC,iC] == 0):
        print('\t Zero on the diagonal, LU failed')
        info = 0
        return M,info
      # eliminate the element
      M[iL,:] = M[iL,:] - M[iL,iC]/M[iC,iC] * M[iC,:]

   # if we succed we return info = 1 and the upper augmetned matrix

  info = 1
  return M,info

In [4]:
########################################################
# Function to backsubstitute the results
# and get the final solution
########################################################
def BS(M):
  # get the size of the matrix
  n = M.shape[0]
  # loop over all the lines
  # starting by the end
  for iL in range(n-1,-1,-1):
    # check if we have diagonal elements on the diagonal
    if(M[iL,iL] == 0):
      print('\t Zero on the diagonal, LU failed')
      info = 0
      return M,info
    # divide the line by the diagonal element of M
    M[iL,:] /= M[iL,iL]
    
    # loop over all the lines that are above this onef
    for iLL in range(iL-1,-1,-1):
      M[iLL,:] -= M[iLL,iL]*M[iL,:]

  info = 1
  return M,info

########################################################
########################################################

In [5]:
# create the matrix A
A = np. array ([[0.9 ,0.3 ,0.1] ,[0.1 ,0.5 ,0.2] , [0.0 ,0.2 ,0.7]])

# create the right-hand side
feed = np. array ([30.0 ,25.0 ,10.0])

M,info = LU(A,feed)
x,info = BS(M)

# print the solution
print(x)

# check the solution
check_sol = np.dot(A,x)
print(check_sol) 

[[ 1.          0.          0.         17.88461538]
 [ 0.          1.          0.         45.96153846]
 [ 0.          0.          1.          1.15384615]]
[[ 0.9  0.3  0.1 30. ]
 [ 0.1  0.5  0.2 25. ]
 [ 0.   0.2  0.7 10. ]]


In [6]:
def resultado(A):
  B = A + A + A
  return B

B = A + A
print(B)
C = resultado(A)
print(C)

# informa a dimensão da matriz (se colocar entre colchetes ele informa a dimensão das linhas ou colunas apenas)
print(A.shape)

[[1.8 0.6 0.2]
 [0.2 1.  0.4]
 [0.  0.4 1.4]]
[[2.7 0.9 0.3]
 [0.3 1.5 0.6]
 [0.  0.6 2.1]]
(3, 3)
